version: '3.1'
networks:
  notification-api:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/16
          gateway: 172.168.0.1

services:
  db:
    container_name: notification-db
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=notification
    networks:
      - notification-api

volumes:
  postgres-data:


