// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
	"notification-system/internal/providers"
)

// Injectors from wire.go:

func InitializeEvent(prefix string) (*App, error) {
	configGorm := providers.ProviderConfig()
	db, err := providers.ProviderDB(configGorm)
	if err != nil {
		return nil, err
	}
	engine := providers.ProviderGinEngine()
	routerGroup := providers.ProviderRouterGroup(engine, prefix)
	app := &App{
		DB:          db,
		RouterGroup: routerGroup,
	}
	return app, nil
}

// wire.go:

type App struct {
	DB          *gorm.DB
	RouterGroup *gin.RouterGroup
}
